(test
 (name test_centl)
 (modules test_centl)
 (deps ../docs/SYNTAX.md)
 (libraries centl_lib alcotest qcheck zarith yojson))

(test
 (name test_adversarial)
 (modules test_adversarial)
 (libraries centl_lib alcotest qcheck zarith yojson))

(test
 (name test_iteration)
 (modules test_iteration)
 (libraries centl_lib alcotest zarith))

(test
 (name test_sequence)
 (modules test_sequence)
 (libraries centl_lib alcotest zarith yojson))

(cram
 (applies_to cli)
 (deps ../src/main.exe fixtures/definitions.centl fixtures/exact.centl))

(cram
 (applies_to installer)
 (enabled_if
  (= %{os_type} Unix))
 (deps
  ../install
  (source_tree fixtures/release)))
