(include_subdirs no)

(library
 (name centl_arb)
 (wrapped false)
 (modules Centl_arb)
 (foreign_stubs
  (language c)
  (names centl_arb_stubs)
  (flags
   (:standard %{env:CENTL_GMP_INCLUDE=} %{env:CENTL_MPFR_INCLUDE=}
    %{env:CENTL_FLINT_INCLUDE=} -Wall -Wextra -Werror)))
 (c_library_flags
  %{env:CENTL_FLINT_LIBRARY=-lflint}
  %{env:CENTL_MPFR_LIBRARY=-lmpfr}
  %{env:CENTL_GMP_LIBRARY=-lgmp}
  -lpthread
  -lm))
