(include_subdirs no)

(library
 (name centl_arb)
 (wrapped false)
 (modules Centl_arb)
 (foreign_stubs
  (language c)
  (names centl_arb_stubs)
  (flags
   (:standard -Wall -Wextra -Werror)))
 (c_library_flags
  %{env:CENTL_FLINT_LIBRARY=-lflint}
  %{env:CENTL_MPFR_LIBRARY=-lmpfr}
  %{env:CENTL_GMP_LIBRARY=-lgmp}
  %{env:CENTL_PTHREAD_LIBRARY=-lpthread}
  %{env:CENTL_MATH_LIBRARY=-lm}))
