(include_subdirs no)

(rule
 (target marsa-cflags.sexp)
 (deps
  (universe)
  ../../scripts/marsa-dune-flags)
 (action
  (with-stdout-to
   %{target}
   (run sh %{dep:../../scripts/marsa-dune-flags} cflags))))

(rule
 (target marsa-libs.sexp)
 (deps
  (universe)
  ../../scripts/marsa-dune-flags)
 (action
  (with-stdout-to
   %{target}
   (run sh %{dep:../../scripts/marsa-dune-flags} libs))))

(library
 (name centl_arb)
 (wrapped false)
 (modules Centl_arb)
 (foreign_stubs
  (language c)
  (names centl_arb_stubs)
  (flags
   (:standard -Wall -Wextra -Werror)
   (:include marsa-cflags.sexp)))
 (c_library_flags
  (:include marsa-libs.sexp)))
