type artifact = {
  json_path : string;
  markdown_path : string;
  workspace_revision : int;
}

let root workspace =
  Filename.concat workspace.Centl_sci_workspace.generated "core-plans"

let write_text path text =
  let temporary = path ^ ".tmp" in
  let channel =
    open_out_gen [ Open_wronly; Open_creat; Open_trunc; Open_text ] 0o600 temporary
  in
  Fun.protect
    ~finally:(fun () -> close_out_noerr channel)
    (fun () ->
      output_string channel text;
      if text = "" || text.[String.length text - 1] <> '\n' then output_char channel '\n';
      flush channel);
  Unix.rename temporary path

let strings values = `List (List.map (fun value -> `String value) values)

let persist workspace ~request ~implementation_layer ~reusable_capabilities
    ~proposed_steps ~trust_notes ~unresolved =
  try
    Centl_sci_workspace.ensure workspace;
    let directory = root workspace in
    Centl_sci_workspace.ensure_directory directory;
    let revision = Centl_sci_workspace.read_revision workspace in
    let stamp = Int64.of_float (Unix.gettimeofday () *. 1_000_000.) in
    let base = Printf.sprintf "core-plan-r%d-%Ld" revision stamp in
    let json_path = Filename.concat directory (base ^ ".json") in
    let markdown_path = Filename.concat directory (base ^ ".md") in
    let json =
      `Assoc
        [
          ("schema_version", `Int 1);
          ("centl_sci_version", `String "0.0.2-Caramels");
          ("scope", `String "downstream_core_change_plan");
          ("request", `String request);
          ("implementation_layer", `String implementation_layer);
          ("reusable_capabilities", strings reusable_capabilities);
          ("proposed_steps", strings proposed_steps);
          ("trust_notes", strings trust_notes);
          ("unresolved", strings unresolved);
          ("workspace_revision", `Int revision);
          ("auto_apply", `Bool false);
          ("auto_publish", `Bool false);
        ]
    in
    Centl_sci_workspace.atomic_write_json json_path json;
    let section title values =
      if values = [] then [ "## " ^ title; ""; "- None"; "" ]
      else [ "## " ^ title; "" ] @ List.map (fun value -> "- " ^ value) values @ [ "" ]
    in
    let markdown =
      String.concat "\n"
        ([
           "# CENTL downstream core-change plan";
           "";
           "Generated by CENTL-SCi v0.0.2-Caramels.";
           "";
           "Request: " ^ request;
           "";
           "Implementation layer: " ^ implementation_layer;
           "";
           "This artifact plans a downstream change only. It does not edit trusted core source, run Git, publish upstream, or confer verified-core assurance.";
           "";
         ]
        @ section "Reusable capabilities" reusable_capabilities
        @ section "Proposed steps" proposed_steps
        @ section "Trust notes" trust_notes
        @ section "Unresolved" unresolved)
    in
    write_text markdown_path markdown;
    Ok { json_path; markdown_path; workspace_revision = revision }
  with Sys_error message | Unix.Unix_error (_, _, message) -> Error message
