type scaffold_kind = Python_adapter | Native_extension

let safe_name name =
  let name = String.trim name in
  Centl_sci_workspace.valid_extension_name name

let write_text_file path text =
  let temporary = path ^ ".tmp" in
  let channel =
    open_out_gen [ Open_wronly; Open_creat; Open_trunc; Open_text ] 0o600 temporary
  in
  Fun.protect
    ~finally:(fun () -> close_out_noerr channel)
    (fun () -> output_string channel text; flush channel);
  Unix.rename temporary path

let scaffold_root workspace = Filename.concat workspace.Centl_sci_workspace.generated "scaffolds"

let create workspace ~kind ~name ~target =
  if not (safe_name name) then Error "invalid scaffold name"
  else
    try
      Centl_sci_workspace.ensure workspace;
      let root = Filename.concat (scaffold_root workspace) name in
      Centl_sci_workspace.ensure_directory root;
      let kind_text, assurance, summary =
        match kind with
        | Python_adapter ->
            ( "python_adapter",
              Centl_sci_workspace.External_backend,
              "Controlled Python interoperability scaffold" )
        | Native_extension ->
            ( "native_extension",
              Centl_sci_workspace.Unverified_generated,
              "Generated native extension scaffold" )
      in
      let manifest =
        `Assoc
          [
            ("schema_version", `Int 1);
            ("name", `String name);
            ("kind", `String kind_text);
            ("target", `String target);
            ("activation", `String "manual_first_pass");
            ("assurance", `String (Centl_sci_workspace.assurance_text assurance));
            ("notes", `String "Caramels scaffold: generated code is not verified core");
          ]
      in
      write_text_file (Filename.concat root "scaffold.json")
        (Yojson.Safe.pretty_to_string manifest ^ "\n");
      write_text_file (Filename.concat root "README.md")
        (String.concat "\n"
           [
             "# " ^ name;
             "";
             "Generated by CENTL-SCi v0.0.2-Caramels BUILD mode.";
             "";
             "Kind: " ^ kind_text;
             "Target: " ^ target;
             "";
             "This scaffold is intentionally inactive until its adapter/native boundary is implemented and validated.";
             "It must not be presented as verified CENTL core functionality.";
             "";
           ]);
      begin match
        Centl_sci_workspace.write_manifest workspace ~name ~enabled:false ~assurance
          ~source:("generated/scaffolds/" ^ name ^ "/scaffold.json") ~summary
      with
      | Error message -> Error message
      | Ok revision -> Ok (root, revision)
      end
    with Sys_error message | Unix.Unix_error (_, _, message) -> Error message

let prepare_upstream workspace =
  try
    Centl_sci_workspace.ensure workspace;
    let revision = Centl_sci_workspace.read_revision workspace in
    let path =
      Filename.concat workspace.generated
        (Printf.sprintf "upstream-contribution-r%d.md" revision)
    in
    let extension_lines =
      Centl_sci_extensions.list workspace
      |> List.map (fun item ->
             Printf.sprintf "- `%s` — enabled=%b — assurance=`%s` — source=`%s`"
               item.name item.enabled item.assurance item.source)
    in
    let body =
      String.concat "\n"
        ([
           "# CENTL downstream contribution preparation";
           "";
           "Generated by CENTL-SCi v0.0.2-Caramels.";
           "";
           Printf.sprintf "Workspace: `%s`" workspace.root;
           Printf.sprintf "Workspace revision: `%d`" revision;
           "";
           "## Local extensions";
           "";
         ]
        @ (if extension_lines = [] then [ "- None" ] else extension_lines)
        @ [
            "";
            "## Required human/upstream review";
            "";
            "- isolate the changes intended for publication";
            "- review assurance and trust-boundary claims";
            "- run the quality gates relevant to the touched implementation layers";
            "- update tests and documentation";
            "- prepare Git commits/PR only after explicit user choice";
            "";
          ])
    in
    write_text_file path body;
    Ok path
  with Sys_error message | Unix.Unix_error (_, _, message) -> Error message
