#!/usr/bin/env python3
"""Analyze full multiplicative square-lift defects and zero-product atoms.

This is a proof-mining companion to MULTIPLICATIVE-DEFECT-QUOTIENT.md and
DEFECT-ZERO-SUM-ATOMS.md.

For every non-squarefree Type A/B modulus 4j-1 up to --k-limit, the script:

1. finds the squarefree ancestor d=4a-1;
2. constructs the Jacobi-positive unit subgroup K_a modulo d;
3. constructs D_a generated by the prime divisors of a;
4. enumerates M_a=K_a/D_a exactly;
5. recovers invariant factors of M_a from p-power torsion counts;
6. maps every prime factor of j to its multiplicative defect class;
7. verifies the exact full-group conservation law;
8. decomposes the defect sequence into minimal zero-product atoms by an exact
   finite search over the (small) prime-factor sequence of j;
9. records quotient signatures, atom lengths, and exceptional examples.

The atom decomposition is not unique. The deterministic decomposition produced
here is a proof-mining diagnostic. The quotient construction and conservation
law are exact theorems independent of this finite run.
"""
from __future__ import annotations

import argparse
import collections
import itertools
import json
import math
from pathlib import Path


def factor(n: int) -> dict[int, int]:
    out: dict[int, int] = {}
    x = n
    p = 2
    while p * p <= x:
        if x % p == 0:
            a = 0
            while x % p == 0:
                x //= p
                a += 1
            out[p] = a
        p = 3 if p == 2 else p + 2
    if x > 1:
        out[x] = out.get(x, 0) + 1
    return out


def squarefree_kernel(n: int) -> int:
    out = 1
    for p, a in factor(n).items():
        if a % 2:
            out *= p
    return out


def jacobi(a: int, n: int) -> int:
    if n <= 0 or n % 2 == 0:
        raise ValueError("Jacobi denominator must be positive odd")
    a %= n
    result = 1
    while a:
        while a % 2 == 0:
            a //= 2
            if n % 8 in (3, 5):
                result = -result
        a, n = n, a
        if a % 4 == 3 and n % 4 == 3:
            result = -result
        a %= n
    return result if n == 1 else 0


def subgroup_generated(modulus: int, generators: list[int]) -> set[int]:
    gens = [g % modulus for g in generators]
    seen = {1 % modulus}
    queue = [1 % modulus]
    while queue:
        x = queue.pop()
        for g in gens:
            y = (x * g) % modulus
            if y not in seen:
                seen.add(y)
                queue.append(y)
    return seen


def quotient_cosets(
    modulus: int,
    K: set[int],
    D: set[int],
) -> tuple[list[int], dict[int, int]]:
    unseen = set(K)
    reps: list[int] = []
    repmap: dict[int, int] = {}
    while unseen:
        seed = min(unseen)
        coset = {(seed * d) % modulus for d in D}
        rep = min(coset)
        reps.append(rep)
        for x in coset:
            repmap[x] = rep
        unseen.difference_update(coset)
    reps.sort()
    return reps, repmap


def exact_log_p(n: int, p: int) -> int:
    e = 0
    while n > 1 and n % p == 0:
        n //= p
        e += 1
    if n != 1:
        raise AssertionError("expected a p-power")
    return e


def quotient_invariant_factors(
    modulus: int,
    reps: list[int],
    D: set[int],
) -> list[int]:
    """Recover invariant factors from counts of p^t-torsion elements."""
    order = len(reps)
    if order == 1:
        return []

    primary_exponents: dict[int, list[int]] = {}
    for p, total_exp in factor(order).items():
        previous_log = 0
        ranks_at_least: list[int] = []
        for t in range(1, total_exp + 1):
            pt = p**t
            count = sum(1 for r in reps if pow(r, pt, modulus) in D)
            log_count = exact_log_p(count, p)
            ranks_at_least.append(log_count - previous_log)
            previous_log = log_count

        exact_counts: list[int] = []
        tail = ranks_at_least + [0]
        for t in range(1, total_exp + 1):
            exact_counts.append(tail[t - 1] - tail[t])

        exponents: list[int] = []
        for exponent, count in enumerate(exact_counts, start=1):
            exponents.extend([exponent] * count)
        exponents.sort()
        primary_exponents[p] = exponents

    rank = max(len(v) for v in primary_exponents.values())
    invariants = [1] * rank
    for p, exponents in primary_exponents.items():
        padded = [0] * (rank - len(exponents)) + exponents
        for i, exponent in enumerate(padded):
            invariants[i] *= p**exponent

    if math.prod(invariants) != order:
        raise AssertionError("invariant factors do not multiply to quotient order")
    if any(invariants[i + 1] % invariants[i] for i in range(len(invariants) - 1)):
        raise AssertionError("invariant factors are not divisibility ordered")
    return invariants


def deterministic_atom_partition(
    sequence: list[int],
    modulus: int,
    D: set[int],
) -> list[list[int]]:
    """Partition one zero-product quotient sequence into minimal atoms.

    Terms are represented by ordinary residues modulo the ancestor modulus. A
    subsequence has quotient product one iff its residue product belongs to D.
    Search is exact and deterministic, increasing first by atom length and then
    lexicographically by index tuple.
    """
    remaining = list(sequence)
    atoms: list[list[int]] = []

    def product_is_neutral(indices: tuple[int, ...]) -> bool:
        x = 1
        for i in indices:
            x = (x * remaining[i]) % modulus
        return x in D

    while remaining:
        chosen: tuple[int, ...] | None = None
        for size in range(1, len(remaining) + 1):
            for indices in itertools.combinations(range(len(remaining)), size):
                if product_is_neutral(indices):
                    chosen = indices
                    break
            if chosen is not None:
                break
        if chosen is None:
            raise AssertionError("zero-product sequence left a non-neutral remainder")

        atom = [remaining[i] for i in chosen]
        # Minimality follows from choosing the smallest possible nonempty size,
        # but recheck all proper nonempty subsets as a regression guard.
        for size in range(1, len(atom)):
            for subset in itertools.combinations(range(len(atom)), size):
                x = 1
                for i in subset:
                    x = (x * atom[i]) % modulus
                if x in D:
                    raise AssertionError("reported atom is not minimal")

        atoms.append(atom)
        chosen_set = set(chosen)
        remaining = [x for i, x in enumerate(remaining) if i not in chosen_set]

    return atoms


def quotient_data(a: int, d: int) -> dict:
    if squarefree_kernel(d) != d:
        raise AssertionError("ancestor modulus is not squarefree")
    units = {x for x in range(1, d) if math.gcd(x, d) == 1}
    K = {x for x in units if jacobi(x, d) == 1}
    D = subgroup_generated(d, list(factor(a)))
    if not D <= K:
        raise AssertionError("ancestor divisor subgroup left Jacobi-positive kernel")

    reps, repmap = quotient_cosets(d, K, D)
    invariants = quotient_invariant_factors(d, reps, D)
    if len(K) // len(D) != len(reps):
        raise AssertionError("quotient order mismatch")

    exact_davenport = None
    if not invariants:
        exact_davenport = 1
    elif len(invariants) <= 2:
        exact_davenport = 1 + sum(n - 1 for n in invariants)
    else:
        prime_support = set()
        for n in invariants:
            prime_support.update(factor(n))
        if len(prime_support) == 1:  # finite p-group
            exact_davenport = 1 + sum(n - 1 for n in invariants)

    return {
        "K": K,
        "D": D,
        "reps": reps,
        "repmap": repmap,
        "invariants": invariants,
        "davenport_exact_when_known": exact_davenport,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--k-limit", type=int, default=1500)
    ap.add_argument("--out", type=Path, default=Path("multiplicative-defect-output"))
    ap.add_argument("--examples", type=int, default=40)
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    cache: dict[tuple[int, int], dict] = {}
    quotient_signature_counts: collections.Counter[tuple[int, ...]] = collections.Counter()
    atom_length_counts: collections.Counter[int] = collections.Counter()
    max_atom_by_signature: dict[tuple[int, ...], int] = collections.defaultdict(int)
    nontrivial_lifts = 0
    trivial_quotient_lifts = 0
    total_lifts = 0
    conservation_checks = 0
    examples: list[dict] = []

    for j in range(1, args.k_limit + 1):
        m = 4 * j - 1
        d = squarefree_kernel(m)
        if d == m:
            continue
        total_lifts += 1
        a = (d + 1) // 4
        key = (a, d)
        if key not in cache:
            cache[key] = quotient_data(a, d)
        data = cache[key]

        invariants = tuple(data["invariants"])
        quotient_signature_counts[invariants] += 1
        if not invariants:
            trivial_quotient_lifts += 1

        seq: list[int] = []
        defectful_terms = 0
        for q, exponent in factor(j).items():
            residue = q % d
            if jacobi(residue, d) != 1:
                raise AssertionError(
                    f"square-lift reciprocity failed at j={j}, q={q}, d={d}"
                )
            if residue not in data["repmap"]:
                raise AssertionError("lift prime residue missing from quotient map")
            seq.extend([residue] * exponent)
            if residue not in data["D"]:
                defectful_terms += exponent

        product = 1
        for residue in seq:
            product = (product * residue) % d
        if product not in data["D"]:
            raise AssertionError(f"multiplicative conservation failed at j={j}")
        conservation_checks += 1

        atoms = deterministic_atom_partition(seq, d, data["D"])
        atom_lengths = [len(atom) for atom in atoms]
        for length in atom_lengths:
            atom_length_counts[length] += 1
            max_atom_by_signature[invariants] = max(
                max_atom_by_signature[invariants], length
            )

        if defectful_terms:
            nontrivial_lifts += 1

        known_D = data["davenport_exact_when_known"]
        if known_D is not None and atom_lengths and max(atom_lengths) > known_D:
            raise AssertionError("observed atom exceeds exact Davenport constant")

        if (
            len(examples) < args.examples
            and (defectful_terms or (known_D is not None and known_D > 2))
        ):
            examples.append(
                {
                    "j": j,
                    "m_j": m,
                    "ancestor_a": a,
                    "ancestor_d": d,
                    "M_invariant_factors": list(invariants),
                    "M_order": len(data["reps"]),
                    "davenport_exact_when_known": known_D,
                    "Omega_j": len(seq),
                    "defectful_prime_terms": defectful_terms,
                    "atom_lengths": atom_lengths,
                }
            )

        if total_lifts % 100 == 0:
            print(
                f"multiplicative-defect progress lifts={total_lifts} j={j} "
                f"ancestors={len(cache)} nontrivial={nontrivial_lifts}",
                flush=True,
            )

    ancestor_rows = []
    for (a, d), data in sorted(cache.items()):
        ancestor_rows.append(
            {
                "a": a,
                "d": d,
                "M_order": len(data["reps"]),
                "M_invariant_factors": data["invariants"],
                "davenport_exact_when_known": data["davenport_exact_when_known"],
            }
        )

    result = {
        "status": "exact finite multiplicative-defect and zero-product-atom analysis",
        "k_limit": args.k_limit,
        "non_squarefree_layers": total_lifts,
        "distinct_squarefree_ancestors": len(cache),
        "trivial_multiplicative_defect_quotient_lifts": trivial_quotient_lifts,
        "lifts_with_nontrivial_prime_defect_terms": nontrivial_lifts,
        "conservation_checks": conservation_checks,
        "quotient_signature_counts": {
            "x".join(map(str, sig)) if sig else "trivial": count
            for sig, count in sorted(quotient_signature_counts.items())
        },
        "atom_length_counts": {
            str(k): v for k, v in sorted(atom_length_counts.items())
        },
        "max_atom_length_by_quotient_signature": {
            "x".join(map(str, sig)) if sig else "trivial": value
            for sig, value in sorted(max_atom_by_signature.items())
        },
        "ancestors": ancestor_rows,
        "examples": examples,
        "claim_boundary": (
            "The multiplicative defect quotient and conservation law are exact. "
            "The deterministic minimal-atom partition is one finite proof-mining decomposition and is not unique. "
            "No finite atom statistic is promoted to a universal bound unless separately proved."
        ),
    }

    (args.out / "multiplicative-defect-atom-analysis.json").write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n"
    )

    report = "# Multiplicative defect and zero-product atoms\n\n"
    report += f"Range: `j <= {args.k_limit}`.\n\n"
    report += f"Non-squarefree Type A/B moduli: **`{total_lifts}`**.\n\n"
    report += f"Distinct squarefree ancestors: **`{len(cache)}`**.\n\n"
    report += f"Exact multiplicative conservation checks: **`{conservation_checks}`**, all passed.\n\n"
    report += f"Lifts with nontrivial multiplicative defect terms: **`{nontrivial_lifts}`**.\n\n"
    report += "Observed minimal-atom lengths in the deterministic decomposition:\n\n"
    report += "```text\n"
    for length, count in sorted(atom_length_counts.items()):
        report += f"{length}: {count}\n"
    report += "```\n\n"
    report += (
        "Every defect sequence was verified to have total product one in the full finite abelian quotient. "
        "Atom lengths are proof-mining diagnostics; Davenport bounds are theorem-level.\n"
    )
    (args.out / "multiplicative-defect-atom-analysis-report.md").write_text(report)
    print(report)


if __name__ == "__main__":
    main()
