(include_subdirs unqualified)

(library
 (name centl_verified)
 (wrapped false)
 (modules Prims FStar_Pervasives_Native Centl_Gcd Centl_Core Centl_Physics)
 (flags
  (:standard -w -8-27))
 (libraries zarith))

(library
 (name centl_lib)
 (wrapped false)
 (modules
  Centl_parser
  Centl_iteration
  Centl_syntax
  Centl_history
  Centl_engine
  Centl_version
  Centl_verify
  Centl_protocol
  Centl_request_queue
  Centl_mcp)
 (libraries centl_verified centl_arb zarith threads unix yojson))

(executable
 (name main)
 (public_name centl)
 (package centl)
 (modules Main)
 (libraries centl_lib threads unix yojson))